#core_model:
#  resource: "../../Engine/Cms/Model/Controller"
#  type: annotation

core_web_cart:
  resource: "../../Engine/Web/Cart/Controller"
  type: annotation

core_web_shop:
  resource: "../../Engine/Web/Shop/Controller"
  type: annotation

core_web_news:
  resource: "../../Engine/Web/News/Controller"
  type: annotation

core_cms_product:
  resource: "../../Engine/Cms/Product/Controller"
  type: annotation

core_cms_order:
  resource: "../../Engine/Cms/Order/Controller"
  type: annotation

core_cms_shipping:
  resource: "../../Engine/Cms/Shipping/Controller"
  type: annotation

core_cms_page:
  resource: "../../Engine/Cms/Page/Controller"
  type: annotation

core_cms_formbuilder:
  resource: "../../Engine/Cms/FormBuilder/Controller"
  type: annotation

core_cms_files:
  resource: "../../Engine/Cms/File/Controller"
  type: annotation

core_cms_imagesize:
  resource: "../../Engine/Cms/ImageSize/Controller"
  type: annotation

core_cms_contentblock:
  resource: "../../Engine/Cms/ContentBlock/Controller"
  type: annotation

core_cms_core:
  resource: "../../Engine/Cms/Core/Controller"
  type: annotation

core_base:
  resource: "../../Engine/Cms/Core/Base/Controller"
  type: annotation
